### ISSUE TITLE
Logo and mascot design

### ISSUE THREAD

**Issue by tansly** [FBDY/bb-gui#13]
We should design a new logo and a mascot in order to resolve #4.

**Comment by tansly** [comment]
After designing the mascot, we should also make it the default sprite before the midterm.

**Comment by tansly** [comment]
We have a new logo! (#62)
Now all it remains is to create a new mascot.

**Comment by bozbalci** [comment]
@tansly mascot has been created, check the PR mentioned above ^^

closing the issue for now
