### ISSUE TITLE
Rebrand the project (bbgui)

### ISSUE THREAD

**Issue by akca** [FBDY/bb-gui#4]

**Comment by tansly** [comment]
Let's deal with npm deployment stuff and get a successful build with the new package names today. After that, we shall remove trademarked stuff and update the README.

**Comment by tansly** [comment]
Made a good deal of progress (https://github.com/FBDY/bb-gui/compare/develop..rebrand). CI/CD is **almost** working as well; I believe everything will start to work as expected when we merge FBDY/bb-blocks#4 and FBDY/bb-vm#4 (bye bye #5).

**Comment by tansly** [comment]
Now, shall we finish all of the rebranding (including logo, mascot etc.) now and merge them all together, or merge the current state and work on the remaining part later? I think we should merge the current state now (to test the CI stuff) and deal with the rest of the stuff later.

**Comment by tansly** [comment]
Things left to do:
* [ ]  Design a logo
* [ ]  Design a mascot (we were thinking of a rabbit)
* [ ]  Remove trademarked items
* [ ]  Replace (maybe some of) the removed items with our designs

**Comment by tansly** [comment]
Cleaning up the menubar now.

**Comment by tansly** [comment]
Menubar, the title and the favicon is dealt with. Logo and mascot needs work.

**Comment by tansly** [comment]
#20 is done. Still waiting for #13.

**Comment by tansly** [comment]
Done. Thanks everyone for their hard work!
:carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: :carrot: 
:rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2: :rabbit2:
